### ISSUE TITLE
[Bug]: Failed to open database at xx dlsym(0x8fe71a70, sqlite3_open_v2): symbol not found

### ISSUE THREAD

**Issue by olimorris** [mrjones2014/legendary.nvim#365] opened 2023-05-08 12:09 UTC
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"
```

### Steps to Reproduce

1. Try and open Legendary with your keymap (in my case `<c-p>`)

### Expected Behavior

Legendary opens with no error and displays my command palette.

### Actual Behavior

I get the following error:

```
[legendary.nvim]
Failed to open database at /Users/Oli/.local/share/nvim/legendary/legendary_frecency.sqlite3: ...li/.local/share/nvim/lazy/sqlite.lua/lua/sqlite/defs.lua:705: dlsym(0x8fe71a70, sqlite3_open_v2): symbol not found
E5108: Error executing lua: ...vim/lazy/legendary.nvim/lua/legendary/api/db/wrapper.lua:101: attempt to index field 'db' (a nil value)
stack traceback:
        ...vim/lazy/legendary.nvim/lua/legendary/api/db/wrapper.lua:101: in function 'transaction'
        ...nvim/lazy/legendary.nvim/lua/legendary/api/db/client.lua:62: in function 'get_item_scores'
        ...nvim/lazy/legendary.nvim/lua/legendary/data/itemlist.lua:123: in function 'sort_inplace'
        ...share/nvim/lazy/legendary.nvim/lua/legendary/ui/init.lua:55: in function 'select_inner'
        ...share/nvim/lazy/legendary.nvim/lua/legendary/ui/init.lua:103: in function 'select'
        ...al/share/nvim/lazy/legendary.nvim/lua/legendary/init.lua:112: in function <...al/share/nvim/lazy/legendary.nvim/lua/legendary/init.lua:110>
```

### Minimal Configuration to Reproduce

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- do not remove the colorscheme! it makes testing nicer
  "folke/tokyonight.nvim",
  {
    "mrjones2014/legendary.nvim",
    dependencies = {
      "stevearc/dressing.nvim",
      "kkharji/sqlite.lua",
    },
    config = {
      select_prompt = "Legendary",
      include_builtin = false,
      include_legendary_cmds = false,
      which_key = { auto_register = false },
    },
    init = function()
      require("legendary").keymaps({
        {
          "<C-p>",
          require("legendary").find,
          hide = true,
          description = "Open Legendary",
          mode = { "n", "v" },
        },
      })
    end,
  },
  -- add any other pugins here
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

require("dressing").setup({
  opts = {
    input = {
      default_prompt = "> ",
      relative = "editor",
      prefer_width = 50,
      prompt_align = "center",
      win_options = { winblend = 0 },
    },
  },
})

require("legendary").keymaps({
  { "<C-y>", "<cmd>%y+<CR>", description = "Copy buffer" },
})

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme! it makes testing nicer
vim.cmd([[colorscheme tokyonight]])
```

### Output from :LegendaryLog

<details>
<summary><code>:LegendaryLog</code> output (click to expand)</summary>

```
[Mon  8 May 13:08:44 2023][legendary.nvim] Performing SQL transaction with following data: {
  params = {},
  query = {
    cmd = 1,
    cmd_data = "item_count"
  }
}
[Mon  8 May 13:08:43 2023][legendary.nvim] Failed to open database at /Users/Oli/.local/share/nvim/legendary/legendary_frecency.sqlite3: ...li/.local/share/nvim/lazy/sqlite.lua/lua/sqlite/defs.lua:705: dlsym(0x8bed1a70, sqlite3_open_v2): symbol not found
[Mon  8 May 13:08:43 2023][legendary.nvim] Initializing frecency database...
[Mon  8 May 13:08:43 2023][legendary.nvim] Launching select UI
[Mon  8 May 13:08:42 2023][legendary.nvim] setup() parsed and applied all configuration.
```
</details>

**Comment by olimorris** [comment] 2023-05-08 12:13
Reverting back to 4fc7d11d03df874ecd7a8cfa6055d7a4ce2cff87 fixes the issue

**Comment by mrjones2014** [comment] 2023-05-08 12:14
Duplicate of #363.

Investigating. Root issue is basically that `sqlite` is not loaded correctly on some setups.

**Closed by mrjones2014** 2023-05-08 12:14 UTC
Labels: bug

**Comment by mrjones2014** [comment] 2023-05-08 12:17
However, I will revert my incorrect fix: https://github.com/mrjones2014/legendary.nvim/pull/366
