### ISSUE TITLE
[Feature]: Classify built-in commands

### ISSUE THREAD

**Issue by hinell** [mrjones2014/legendary.nvim#262] opened 2022-12-16 00:25 UTC
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

I propose to classify (add prefix) to built in commands. descriptions so it's easier to navigate:

```
Navigation: go to ...
Tabs: go to the last ...
Window: vertically split
Motion: ...
etc
```

**Comment by hinell** [comment] 2022-12-16 18:04
Well item groups won't be as conveniet as simple list.... but let's see.

**Comment by mrjones2014** [comment] 2023-02-13 15:22
Closing as duplicate of #306

**Closed by mrjones2014** 2023-02-13 15:22 UTC
Labels: enhancement

**Comment by hinell** [comment] 2023-05-18 19:12
@mrjones2014 Sorry, but these are different. When I mean classify, I mean "append a name to the specific groups of functionality". E.g.:

```
Tabs: previous tab
Tabs: next tab
Tabs: close
Buffer: change a line
...

```

**Comment by mrjones2014** [comment] 2023-05-18 22:27
To me that's the exact purpose of item groups

**Comment by hinell** [comment] 2023-05-19 08:19
@mrjones2014 Item groups would be iconveniet to search across.
