### ISSUE TITLE
Use `nvim_set_keymap`'s `desc` option when creating a new mapping.

### ISSUE THREAD

**Issue by bennypowers** [mrjones2014/legendary.nvim#139] opened 2022-04-21 09:32 UTC
> In case which-key adds support for the `desc` option when creating a new mapping. Wouldn't that make the integration much easier ? I believe you wouldn't need any specific code for which-key in your plugin.
> 
> For reference:
> folke/which-key.nvim#253 
> folke/which-key.nvim#242

_Originally posted by @rafamadriz in https://github.com/mrjones2014/legendary.nvim/issues/78#issuecomment-1100942567_

The goal of this issue is to allow users to set their keymaps entirely with `nvim_set_keymap` or `nvim_buf_set_keymap` without requiring them to use which-key or legendary's wrappers at all.

**Comment by mrjones2014** [comment] 2022-04-21 10:14
Duplicate of #39 

There's some comments there about why that's not as simple as it seems.

**Closed by mrjones2014** 2022-04-21 10:14 UTC
