### ISSUE TITLE
[Feature]: Allow to add all user commands

### ISSUE THREAD

**Issue by gkzhb** [mrjones2014/legendary.nvim#141] opened 2022-04-29 04:02 UTC
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

Now users have to manually register commands(from other plugins) for `legendary.nvim`. It's not convenient to use this plugin as command fuzzy finder and trigger commands.

I believe we can provide a setup option to allow users to add all the user commands to `legendary.nvim` with lua API `vim.api.nvim_get_commands` just like telescope `builtin.commands`.

**Comment by mrjones2014** [comment] 2022-04-29 10:40
Duplicate of #39

**Closed by mrjones2014** 2022-04-29 10:40 UTC
Labels: enhancement
